kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: omero-frontend-build-test
  namespace: core-omero-test
  uid: 04e3c182-e71a-41b2-ba9e-2bd0f3972064
  resourceVersion: '4292780247'
  generation: 18
  creationTimestamp: '2025-01-21T12:22:06Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2025-01-21T12:28:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2025-01-21T15:04:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: core-omero-test
      name: 'omero-frontend-test:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/CCI-GU-Sweden/Omero_GU'
      ref: test/main
    contextDir: /
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: omero-gu-webhook
  runPolicy: Serial
status:
  lastVersion: 31
