kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '20'
    image.openshift.io/triggers: |-
      [
       {
         "from": {
           "kind": "ImageStreamTag",
           "name": "omero-frontend-flask-app:dev"
         },
         "fieldPath": "spec.template.spec.containers[?(@.name=='flask-app')].image"
       }
      ]
  resourceVersion: '4290197160'
  name: flask-app
  uid: 6d319e1c-35c6-44ad-af67-c4069ae7484d
  creationTimestamp: '2024-12-18T14:42:19Z'
  generation: 24
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2024-12-18T14:42:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"flask-app"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"JAVA_OPTS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/.cache"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/app/omero/logs"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/app/omero/uploads"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/omero"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"logs"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"slash-cache"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"slash-omero"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"upload"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2025-01-20T13:14:06Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:image.openshift.io/triggers': {}
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.openshift.io/restartedAt': {}
            'f:spec':
              'f:containers':
                'k:{"name":"flask-app"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-01-20T13:14:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: core-omero-dev
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
        deployment: flask-app
      annotations:
        openshift.openshift.io/restartedAt: '2025-01-16T12:37:19.972Z'
    spec:
      volumes:
        - name: slash-omero
          persistentVolumeClaim:
            claimName: flask-slash-omero
        - name: logs
          persistentVolumeClaim:
            claimName: flask-logs
        - name: upload
          persistentVolumeClaim:
            claimName: flask-upload
        - name: slash-cache
          persistentVolumeClaim:
            claimName: flask-slash-cache
      containers:
        - name: flask-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/core-omero-dev/omero-frontend-flask-app:dev
          env:
            - name: JAVA_OPTS
              value: >-
                -Djava.util.prefs.userRoot=/omero/userPrefs
                -Djava.util.prefs.systemRoot=/omero/systemPrefs
          resources: {}
          volumeMounts:
            - name: slash-omero
              mountPath: /omero
            - name: upload
              mountPath: /app/omero/uploads
            - name: logs
              mountPath: /app/omero/logs
            - name: slash-cache
              mountPath: /.cache
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 24
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-01-16T09:49:45Z'
      lastTransitionTime: '2025-01-16T09:49:45Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-01-20T13:14:35Z'
      lastTransitionTime: '2025-01-16T12:29:42Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "flask-app-77f9c7cf9b" has successfully progressed.
