name: run pytests with tox

on: [push, pull_request]

jobs:
  test:
    name: "unittests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e py -- -m "not manual"
